# SPDX-License-Identifier: GPL-2.0-only
dtb-$(CONFIG_ARCH_INTEL_SOCFPGA) += socfpga_agilex_socdk.dtb \
				socfpga_agilex_socdk_nand.dtb \
				socfpga_n5x_socdk.dtb
dtb-$(CONFIG_ARCH_KEEMBAY) += keembay-evm.dtb

dtb-$(CONFIG_ARCH_THUNDERBAY) += hddl_hybrid_4s.dtb \
				 hddl_hybrid_2s_02.dtb \
				 hddl_hybrid_2s_03.dtb \
				 hddl_hybrid_2s_12.dtb \
				 hddl_hybrid_2s_13.dtb
