/*
 * Copyright (c) 2016--2017 Intel Corporation.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version
 * 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */
#if IS_ENABLED(CONFIG_VIDEO_INTEL_IPU5)

#ifndef INTEL_IPU5_PSYS_RESOURCES_H
#define INTEL_IPU5_PSYS_RESOURCES_H

/* ia_css_psys_process_group_cmd_impl.h */
#define	IPU_FW_PSYS_N_PADDING_UINT8_IN_PROCESS_STRUCT			4
#define	IPU_FW_PSYS_N_PADDING_UINT8_IN_PROCESS_GROUP_STRUCT		4

/* ia_css_terminal_base_types.h */
#define IPU_FW_PSYS_N_PADDING_UINT8_IN_TERMINAL_STRUCT			5

/* ia_css_terminal_types.h */
#define IPU_FW_PSYS_N_PADDING_UINT8_IN_PARAM_TERMINAL_STRUCT		6

/* ia_css_psys_terminal.c */
#define	IPU_FW_PSYS_N_PADDING_UINT8_IN_DATA_TERMINAL_STRUCT		3

/* ia_css_program_group_data.h */
#define	IPU_FW_PSYS_N_PADDING_UINT8_IN_FRAME_DESC_STRUCT		3
#define IPU_FW_PSYS_N_FRAME_PLANES					6
#define IPU_FW_PSYS_N_PADDING_UINT8_IN_FRAME_STRUCT			4

/* ia_css_psys_buffer_set.h */
#define IPU_FW_PSYS_N_PADDING_UINT8_IN_BUFFER_SET_STRUCT	5

enum {
	IPU_FW_PSYS_TRANSFER_VMEM0_TYPE_ID = 0,
	IPU_FW_PSYS_TRANSFER_VMEM1_TYPE_ID,
	IPU_FW_PSYS_LB_VMEM_TYPE_ID,
	IPU_FW_PSYS_DMEM_TYPE_ID,
	IPU_FW_PSYS_VMEM_TYPE_ID,
	IPU_FW_PSYS_BAMEM_TYPE_ID,
	IPU_FW_PSYS_PMEM_TYPE_ID,
	IPU_FW_PSYS_N_MEM_TYPE_ID
};

enum intel_ipu_mem_id {
	IPU_FW_PSYS_VMEM0_ID = 0,
	IPU_FW_PSYS_VMEM1_ID, /* ISP1 VMEM */
	IPU_FW_PSYS_VMEM2_ID, /* ISP2 VMEM */
	IPU_FW_PSYS_TRANSFER_VMEM0_ID,
	IPU_FW_PSYS_TRANSFER_VMEM1_ID,
	IPU_FW_PSYS_LB_VMEM_ID,
	IPU_FW_PSYS_BAMEM0_ID,
	IPU_FW_PSYS_BAMEM1_ID, /* ISP1 BAMEM */
	IPU_FW_PSYS_BAMEM2_ID, /* ISP2 BAMEM */
	IPU_FW_PSYS_DMEM0_ID,
	IPU_FW_PSYS_DMEM1_ID,
	IPU_FW_PSYS_DMEM2_ID,
	IPU_FW_PSYS_DMEM3_ID,
	IPU_FW_PSYS_DMEM4_ID, /* ISP1 Dmem */
	IPU_FW_PSYS_DMEM5_ID, /* ISP2 Dmem */
	IPU_FW_PSYS_PMEM0_ID,
	IPU_FW_PSYS_PMEM1_ID, /* ISP1 PMEM */
	IPU_FW_PSYS_PMEM2_ID, /* ISP2 PMEM */
	IPU_FW_PSYS_N_MEM_ID
};

enum {
	IPU_FW_PSYS_DEV_CHN_DMA_EXT0_ID = 0,
	IPU_FW_PSYS_DEV_CHN_GDC_ID,
	IPU_FW_PSYS_DEV_CHN_DMA_EXT1_READ_ID,
	IPU_FW_PSYS_DEV_CHN_DMA_EXT1_WRITE_ID,
	IPU_FW_PSYS_DEV_CHN_DMA_INTERNAL_ID,
	IPU_FW_PSYS_DEV_CHN_DMA_IPFD_ID,
	IPU_FW_PSYS_DEV_CHN_DMA_ISA_ID,
	IPU_FW_PSYS_DEV_CHN_DMA_FW_ID,
	IPU_FW_PSYS_N_DEV_CHN_ID
};

enum {
	IPU_FW_PSYS_SP_CTRL_TYPE_ID = 0,
	IPU_FW_PSYS_SP_SERVER_TYPE_ID,
	IPU_FW_PSYS_VP_TYPE_ID,
	IPU_FW_PSYS_ACC_PSA_TYPE_ID,
	IPU_FW_PSYS_ACC_ISA_TYPE_ID,
	IPU_FW_PSYS_ACC_OSA_TYPE_ID,
	IPU_FW_PSYS_GDC_TYPE_ID,
	IPU_FW_PSYS_N_CELL_TYPE_ID
};

enum {
	IPU_FW_PSYS_SP0_ID = 0,
	IPU_FW_PSYS_SP1_ID,
	IPU_FW_PSYS_SP2_ID,
	IPU_FW_PSYS_VP0_ID,
	IPU_FW_PSYS_VP1_ID,
	IPU_FW_PSYS_VP2_ID,
	IPU_FW_PSYS_ACC0_ID,
	IPU_FW_PSYS_ACC1_ID,
	IPU_FW_PSYS_ACC2_ID,
	IPU_FW_PSYS_ACC3_ID,
	IPU_FW_PSYS_ACC4_ID,
	IPU_FW_PSYS_ACC5_ID,
	IPU_FW_PSYS_ACC6_ID,
	IPU_FW_PSYS_ACC7_ID,
	IPU_FW_PSYS_ACC8_ID,
	IPU_FW_PSYS_ACC9_ID,
	IPU_FW_PSYS_ACC10_ID,
	IPU_FW_PSYS_ACC11_ID,
	IPU_FW_PSYS_ACC12_ID,
	IPU_FW_PSYS_GDC0_ID,
	IPU_FW_PSYS_N_CELL_ID
};

enum {
	IPU_FW_PSYS_DEV_DFM_BB_FULL_PORT_ID = 0,
	IPU_FW_PSYS_DEV_DFM_BB_EMPTY_PORT_ID,
	IPU_FW_PSYS_DEV_DFM_LB_FULL_PORT_ID,
	IPU_FW_PSYS_DEV_DFM_LB_EMPTY_PORT_ID,
	IPU_FW_PSYS_N_DEV_DFM_ID
};

#define IPU_FW_PSYS_VMEM0_MAX_SIZE		   0x0800
#define IPU_FW_PSYS_VMEM1_MAX_SIZE		   0x0800
#define IPU_FW_PSYS_VMEM2_MAX_SIZE		   0x0800
#define IPU_FW_PSYS_TRANSFER_VMEM0_MAX_SIZE	   0x0400
#define IPU_FW_PSYS_TRANSFER_VMEM1_MAX_SIZE	   0x0400
#define IPU_FW_PSYS_LB_VMEM_MAX_SIZE		   0x0400
#define IPU_FW_PSYS_BAMEM0_MAX_SIZE		   0x0800
#define IPU_FW_PSYS_BAMEM1_MAX_SIZE		   0x0800
#define IPU_FW_PSYS_BAMEM2_MAX_SIZE		   0x0800
#define IPU_FW_PSYS_DMEM0_MAX_SIZE		   0x4000
#define IPU_FW_PSYS_DMEM1_MAX_SIZE		   0x1000
#define IPU_FW_PSYS_DMEM2_MAX_SIZE		   0x1000
#define IPU_FW_PSYS_DMEM3_MAX_SIZE		   0x1000
#define IPU_FW_PSYS_DMEM4_MAX_SIZE		   0x1000
#define IPU_FW_PSYS_DMEM5_MAX_SIZE		   0x1000
#define IPU_FW_PSYS_PMEM0_MAX_SIZE		   0x0500
#define IPU_FW_PSYS_PMEM1_MAX_SIZE		   0x0500
#define IPU_FW_PSYS_PMEM2_MAX_SIZE		   0x0500

#define IPU_FW_PSYS_DEV_CHN_DMA_EXT0_MAX_SIZE		(30)
#define IPU_FW_PSYS_DEV_CHN_GDC_MAX_SIZE		(4)
#define IPU_FW_PSYS_DEV_CHN_DMA_EXT1_READ_MAX_SIZE	(30)
#define IPU_FW_PSYS_DEV_CHN_DMA_EXT1_WRITE_MAX_SIZE	(20)
#define IPU_FW_PSYS_DEV_CHN_DMA_INTERNAL_MAX_SIZE	(4)
#define IPU_FW_PSYS_DEV_CHN_DMA_IPFD_MAX_SIZE		(5)
#define IPU_FW_PSYS_DEV_CHN_DMA_ISA_MAX_SIZE		(2)
#define IPU_FW_PSYS_DEV_CHN_DMA_FW_MAX_SIZE		(1)

#endif
#endif /* IPU5 */
