# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2012-2019, Intel Corporation. All rights reserved.
userprogs-always-y += mei-amt-version

obj-$(CONFIG_SAMPLE_INTEL_MEI_DAL_TEST) := dal_test.o

always-y := $(userprogs)

userccflags += -I usr/include
