#
# Makefile for KeemBay xlink Linux driver
#
CFLAGS_xlink-trace.o := -I$(src)
obj-$(CONFIG_XLINK_CORE) += xlink.o
xlink-objs += xlink-core.o xlink-multiplexer.o xlink-dispatcher.o xlink-platform.o xlink-trace.o
