# Copyright (C) 2020 Intel Corporation
# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for intel tsens Thermal Linux driver
#

obj-$(CONFIG_INTEL_TSENS_LOCAL_HOST)	+= intel_tsens_thermal.o
obj-$(CONFIG_INTEL_TSENS_IA_HOST)	+= intel_tsens_host.o
