#
# Makefile for KeemBay Thermal Linux driver
#

obj-$(CONFIG_INTEL_TSENS)       += intel_tsens_thermal.o
obj-$(CONFIG_INTEL_TSENS_HOST) 	+= intel_tsens_host.o
obj-$(CONFIG_KEEMBAY_THERMAL)	+= keembay_thermal.o
obj-$(CONFIG_KEEMBAY_THERMAL)	+= keembay_cooling.o
