hantro-objs = hantro_drv.o hantro_fs.o hantro_drm.o hantro_dmabuf.o hantro_enc.o hantro_dec.o hantro_fence.o hantro_cache.o hantro_dec400.o hantro_devicemgr.o trace.o
obj-$(CONFIG_DRM_HANTRO_UNIFY) += hantro.o
CFLAGS_trace.o := -I$(src)
