# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2016-2019, Intel Corporation

ccflags-y += -D__CHECK_ENDIAN__

obj-$(CONFIG_INTEL_MEI_DAL) += mei_dal.o
mei_dal-objs += acp_parser.o
mei_dal-objs += dal_class.o
