obj-$(CONFIG_XLINK_USB_LH_DRIVER)	+= g_serial_vpu_usb.o
g_serial_vpu_usb-y	:= serial_vpu_usb.o
g_serial_vpu_usb-y += mxlk_interface.o

obj-$(CONFIG_USB_U_XLINK)	+= usb_u_xlink.o
usb_u_xlink-y			:= u_xlink.o

obj-$(CONFIG_USB_F_VPUUSB)	+= usb_f_vpuusb.o
usb_f_vpuusb-y			:= f_vpuusb.o
