# Copyright (C) 2020 Intel Corporation
# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_HDDL_DEVICE_CLIENT)	+= hddl_device_client.o
hddl_device_client-objs			+= hddl_device_lh.o hddl_device.o
obj-$(CONFIG_HDDL_DEVICE_SERVER)	+= hddl_device_server.o
hddl_device_server-objs			+= hddl_device_rh.o hddl_device.o
