# Copyright (C) 2019 Intel Corporation
# SPDX-License-Identifier: GPL-2.0-only
#     Makefile for KeemBay VPUSMM
#
obj-$(CONFIG_HDDL_DEVICE_CLIENT) += hddl_device_client.o
obj-$(CONFIG_HDDL_DEVICE_SERVER) += hddl_device_server.o
